sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # ppa:ubuntu-toolchain-r/test
    packages:
      - libbz2-dev
      - libhttp-parser-dev
      - libssh2-1-dev
      - libssl-dev
      - gcc-5
      - g++-5
      # GUI dependencies
      - libx11-dev
      - libgtk2.0-dev
      - libnss3-dev
      - libgconf2-dev
      - libxss-dev
      - libasound2-dev
      - libxtst-dev

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/bower_components
    - $HOME/boost_1_67_0/boost
    - $HOME/boost_1_67_0/stage/lib
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - export CXXFLAGS="-fPIC" CFLAGS="-fPIC"
  # Install Node.js dependencies
  - yarn install
  # Add local binary path to PATH
  - export PATH="./node_modules/.bin:$PATH"
  # Install runtime dependencies using Bower
  - bower install
  - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.0.0/install_boost.py
  - python install_boost.py --directory ~ --boost-version 1.67.0 filesystem locale system
  # Install packages for generating documentation
  - pip install --user sphinx sphinx_rtd_theme
  # Add sphinx-build to PATH
  - export PATH="$HOME/.local/bin:$PATH"
  # Get CMake (version available in repositories is too old, needs to be 3.1+)
  - wget --no-check-certificate https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.7.2-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.7.2-Linux-x86_64/bin:$PATH
  - wget https://github.com/WrinklyNinja/svg_to_ico/releases/download/0.1.0/svg_to_ico.tar.xz
  - tar -xJf svg_to_ico.tar.xz

before_script:
  - mkdir build
  - ./svg_to_ico -i resources/icon.svg -o build/icon/icon.ico
  # Move into the cloned LOOT repo build path.
  - cd build
  # Link dynamically to the C++ standard library runtime.
  - cmake .. -DBOOST_ROOT=~/boost_1_67_0

script:
  - make all
  - ./loot_gui_tests

after_success:
  - cd $TRAVIS_BUILD_DIR
  # Get the full repo history before trying to run the archiver.
  - git fetch --unshallow
  - node scripts/potomo.js
  - sphinx-build -b html docs build/docs/html
  - node scripts/archive.js
  # Need to replace the HEAD branch descriptor in the archive filenames
  - for ARCHIVE in build/*.tar.xz; do mv $ARCHIVE $(echo $ARCHIVE | sed "s/HEAD/$TRAVIS_BRANCH/"); done
  # Need to replace the Bintray config files' version placeholders.
  - VERSION=$(ls build/loot_*.tar.xz | sed 's/build\/loot_//;s/.tar.xz//;')
  - sed -i "s/REPLACE_THIS_VERSION/$VERSION/" scripts/travis/loot.bintray.json

deploy:
  - provider: bintray
    file: scripts/travis/loot.bintray.json
    user: wrinklyninja
    key:
      secure: "CyJpCbkO4pK+h4ZFDqwS3FZNwTaY7638IT7uzVKhGQV2CD9nMR7mb9bL6DG/Uxs91MuBeCu8RwzXtK5IVmPkH5AbMO95JMsjor+t8lT6AHhjvgmAhOBXJa5qMbFBFbLQErTdudHIcOxgjyjA5vqt5Zf0DlWty7WnE10WoU/O7qg="
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
