sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # ppa:ubuntu-toolchain-r/test
    packages:
      - libbz2-dev
      - libhttp-parser-dev
      - libssh2-1-dev
      - libssl-dev
      - gcc-8
      - g++-8
      # GUI dependencies
      - libx11-dev
      - libgtk2.0-dev
      - libnss3-dev
      - libgconf2-dev
      - libxss-dev
      - libasound2-dev
      - libxtst-dev

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $HOME/boost_1_67_0/boost
    - $HOME/boost_1_67_0/stage/64/lib
  yarn: true

before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  # Use GCC 5.
  - export CXX="g++-8" CC="gcc-8"
  # Install Node.js dependencies
  - yarn install
  # Add local binary path to PATH
  - export PATH="./node_modules/.bin:$PATH"
  # Install Boost
  - wget https://raw.githubusercontent.com/Ortham/ci-scripts/1.5.0/install_boost.py
  - python install_boost.py --directory ~ --boost-version 1.67.0 -a 64 -t gcc-8 locale system
  # Install packages for generating documentation
  - pip install --user -r docs/requirements.txt
  # Add sphinx-build to PATH
  - export PATH="$HOME/.local/bin:$PATH"

before_script:
  - mkdir build
  # Move into the cloned LOOT repo build path.
  - cd build
  # Link dynamically to the C++ standard library runtime.
  - cmake .. -DBOOST_ROOT=~/boost_1_67_0 -DBOOST_LIBRARYDIR=~/boost_1_67_0/stage/64/lib

script:
  - make all
  - ./loot_gui_tests

after_success:
  - cd $TRAVIS_BUILD_DIR
  # Get the full repo history before trying to run the archiver.
  - git fetch --unshallow
  - node scripts/potomo.js
  - sphinx-build -b html docs build/docs/html
  - node scripts/archive.js
  # Need to replace the HEAD branch descriptor in the archive filenames
  - for ARCHIVE in build/*.tar.xz; do mv $ARCHIVE $(echo $ARCHIVE | sed "s/HEAD/$TRAVIS_BRANCH/"); done
  # Need to replace the Bintray config files' version placeholders.
  - VERSION=$(ls build/loot_*.tar.xz | sed 's/build\/loot_//;s/.tar.xz//;')
  - sed -i "s/REPLACE_THIS_VERSION/$VERSION/" scripts/travis/loot.bintray.json

deploy:
  - provider: bintray
    file: scripts/travis/loot.bintray.json
    user: wrinklyninja
    key:
      secure: "CyJpCbkO4pK+h4ZFDqwS3FZNwTaY7638IT7uzVKhGQV2CD9nMR7mb9bL6DG/Uxs91MuBeCu8RwzXtK5IVmPkH5AbMO95JMsjor+t8lT6AHhjvgmAhOBXJa5qMbFBFbLQErTdudHIcOxgjyjA5vqt5Zf0DlWty7WnE10WoU/O7qg="
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
