os: Visual Studio 2015

version: "{build}-{branch}"

configuration: Release

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

environment:
  github_auth_token:
    secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH
  bintray_auth_token:
    secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr

install:
  - ps: Install-Product node LTS
  - python -m pip install sphinx sphinx_rtd_theme
  - yarn install
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/2.0.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/WrinklyNinja/svg_to_ico/releases/download/0.1.0/svg_to_ico.7z', "$env:APPVEYOR_BUILD_FOLDER\svg_to_ico.7z")
  - 7z e -y svg_to_ico.7z


before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - .\svg_to_ico.exe -i resources\icon.svg -o build\icon\icon.ico
  - cd build
  - cmake .. -G "Visual Studio 14 2015" -DBOOST_ROOT="C:\Libraries\boost_1_67_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_67_0\lib32-msvc-14.0" -DMSVC_STATIC_RUNTIME=ON

build:
  verbosity: minimal
  project: '$(APPVEYOR_BUILD_FOLDER)\build\LOOT.sln'

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - yarn lint
  - yarn test
  - cd %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%
  - .\loot_gui_tests.exe --gtest_output=xml:loot_gui_tests.xml

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\Python27\Scripts\sphinx-build -b html docs build\docs\html
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --abbrev=7) | Out-String) -replace "`n|`r", ""
  - ps: $env:PATH = "$env:PATH;C:\cygwin\bin\"
  - node scripts\potomo.js
  - ps: scripts\appveyor\build_installer.ps1
  - node scripts\archive.js

artifacts:
  - path: build\loot_$(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH).7z
    name: LOOT
  - path: build\LOOT Installer.exe
    name: installer

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr
    subject: loot
    repo: snapshots
    package: loot
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    override: true
    artifact: LOOT

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: LOOT v$(APPVEYOR_REPO_TAG_NAME)
    description: |
      Requires Windows 7 or later and the [MSVC 2015 x86 redistributable](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe), and [7-Zip](https://www.7-zip.org/) to extract the archives. The list of changes can be found [here](https://loot.readthedocs.io/en/$(APPVEYOR_REPO_TAG_NAME)/app/changelog.html).
    auth_token:
      secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH
    artifact: LOOT,installer
    draft: false
    force_update: true
    on:
      appveyor_repo_tag: true

on_success:
  - ps: python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -g loot/loot -b loot/snapshots/loot -u wrinklyninja -k $env:bintray_auth_token -t $env:github_auth_token -n 30
  - ps: scripts\appveyor\update_masterlist_branches.ps1

on_finish:
  - ps: (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "$($env:APPVEYOR_BUILD_FOLDER)\build\$($env:CONFIGURATION)\loot_gui_tests.xml")
