# Example Default LOOT Settings File
# This file is written in YAML <http://www.yaml.org/>.

language:            eng    # One of 'eng', 'spa', 'rus' or ''.

game:                auto   # auto, or one of the 'folder' values below.
lastGame:            auto   # auto, or one of the 'folder' values below.
enableDebugLogging:  false
updateMasterlist:    true

# Games. The four types are 'Oblivion', 'Skyrim', 'Fallout3' and 'FalloutNV'. They correspond to each base game's libespm and libloadorder settings.
games:
  - folder: Oblivion
    name: "TES IV: Oblivion"
    type: Oblivion
    master: Oblivion.esm
    repo: https://github.com/loot/oblivion.git
    branch: master
    path: ~
    registry: Software\Bethesda Softworks\Oblivion\Installed Path

  - folder: Skyrim
    name: "TES V: Skyrim"
    type: Skyrim
    master: Skyrim.esm
    repo: https://github.com/loot/skyrim.git
    branch: master
    path: ~
    registry: Software\Bethesda Softworks\Skyrim\Installed Path

  - folder: Fallout3
    name: Fallout 3
    type: Fallout3
    master: Fallout3.esm
    repo: https://github.com/loot/fallout3.git
    branch: master
    path: ~
    registry: Software\Bethesda Softworks\Fallout3\Installed Path

  - folder: FalloutNV
    name: "Fallout: New Vegas"
    type: FalloutNV
    master: FalloutNV.esm
    repo: https://github.com/loot/falloutnv.git
    branch: master
    path: ~
    registry: Software\Bethesda Softworks\FalloutNV\Installed Path

  - folder: Nehrim
    name: Nehrim - At Fate's Edge
    type: Oblivion
    master: Nehrim.esm
    repo: https://github.com/loot/oblivion.git
    branch: master
    path: ~
    registry: Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1\InstallLocation
